/**
 * Created by Joe on 2017/1/22.
 */
var contingency="";
function addFavorite(b,a){try{window.external.addFavorite(b,a);
}catch(c){try{window.sidebar.addPanel(a,b,"");
}catch(c){alertWarningMsg("123");
}}}function elementHover(c,a,b){$(c).hover(function(){$(this).addClass(b);
    $(a).fadeIn("slow");
},function(){$(this).removeClass(b);
    $(a).fadeOut("slow");
});}function tabs(c,d,b){var a=0;
    if(b===true){$(c).mouseover(function(){a=$(c).index(this);
        tabsFun(a,c,d);
        return false;
    });}else{$(c).click(function(){a=$(c).index(this);
        tabsFun(a,c,d);
        return false;
    });}}function tabsFun(b,a,c){$(a).removeClass("current").eq(b).addClass("current");
    $(c).removeClass("current").eq(b).addClass("current");
}function backToTop(b){var c=$(b);
    c.click(function(){$("html, body").animate({scrollTop:0},120);
    });var a=function(){var e=$(document);
        var d=e.scrollTop(),f=e.height();
        (d>0)?c.show():c.hide();
        if(!window.XMLHttpRequest){c.css("top",d+425);
        }};$(window).bind("scroll",a);
}(function(a){a.fn.extend({Scroll:function(c,f){if(!c){var c={};
}var e=this.eq(0).find("ul:first");
    var b=e.find("li:first").outerHeight();
    line=c.line?parseInt(c.line,10):parseInt(this.height()/b,10),speed=c.speed?parseInt(c.speed,10):500,timer=c.timer?parseInt(c.timer,10):3000;
    if(line==0){line=1;
    }var d=0-line*b;
    scrollUp=function(){e.animate({marginTop:d},speed,function(){for(i=1;
                                                                     i<=line;i++){e.find("li:first").appendTo(e);
    }e.css({marginTop:0});
    });};e.hover(function(){clearInterval(timerID);
    },function(){timerID=setInterval("scrollUp()",timer);
    }).mouseout();
}});})(jQuery);
$(document).ready(function(){try{$("#J_answer_list").Scroll({line:1,speed:1000,timer:3000});
}catch(a){}});
$(function(){var g=$("#J_recommend-read .recommend-read-list").width();
    var d=1;var c=1;
    var a=$(".recommend-read-list .read-item").length;
    var f=Math.ceil(a/c);
    var b=$(".recommend-read-list").width();
    var e=$(".recommend-read-list .read-scroll");
    $(".read-scroll").css("width",g*(a));
    $(".btn-re-next").click(function(){if(!e.is(":animated")){if(d==f){e.animate({left:0},800);
        d=1;}else{e.animate({left:"-="+b},800);
        d++;}}});$(".btn-re-prev").click(function(){if(!e.is(":animated")){if(d==1){e.animate({left:"-="+b*(f-1)},800);
        d=f;}else{e.animate({left:"+="+b},800);
        d--;}}});$(".list").hover(function(){if(!$(this).hasClass("active")){$(this).addClass("hover");
        $(this).find(".btn1").show();
    }},function(){$(this).removeClass("hover");
        $(this).find(".btn1").hide();
    });$(".list").click(function(){if($(this).hasClass("active")){$(this).removeClass("active");
        $(this).find(".hf-box").slideUp();
        $(this).find(".btn1").show();
    }else{$(this).addClass("active").siblings().removeClass("active").find(".hf-box").slideUp("fast");
        $(this).find(".hf-box").slideDown();
        $(this).find(".btn1").hide();
    }});$(".pack-up").click(function(){$(this).parents(".hf-box").slideUp();
    });$(".question-title a,.hf-box,.ctr-link").click(function(h){h.stopPropagation();
    });$(".check_box input").toggle(function(){$(this).parent().addClass("aaico-on");
    },function(){$(this).parent().removeClass("aaico-on");
    });});var slider=function(b,a){this.$ctn=$("#"+b);
    this.$focus=$("#"+a);
    this.$adLis=null;
    this.$btns=null;
    this.switchSpeed=3;
    this.animateSpeed=500;
    this.defOpacity=1;
    this.crtIndex=0;
    this.adLength=0;
    this.timerSwitch=null;
    this.init();
};slider.prototype={fnNextIndex:function(){return(this.crtIndex>=this.adLength-1)?0:this.crtIndex+1;
},fnPreIndex:function(){return(this.crtIndex<=0)?(this.adLength-1):this.crtIndex-1;
},fnSwitch:function(b){if(this.crtIndex==b){return;
}this.$adLis.css("zIndex",0);
    this.$adLis.filter(":eq("+this.crtIndex+")").css("zIndex",2);
    this.$adLis.filter(":eq("+b+")").css("zIndex",1);
    this.$btns.removeClass("on");
    this.$btns.filter(":eq("+b+")").addClass("on");
    var a=this;
    $(this.$adLis[this.crtIndex]).animate({opacity:0},a.animateSpeed,function(){a.crtIndex=b;
        $(this).css({opacity:a.defOpacity,zIndex:0});
    });},fnAutoPlay:function(){this.fnSwitch(this.fnNextIndex());
},fnPlay:function(){var a=this;
    a.timerSwitch&&clearInterval(a.timerSwitch);
    a.timerSwitch=window.setInterval(function(){a.fnAutoPlay();
    },a.switchSpeed*1000);
},fnStopPlay:function(){clearInterval(this.timerSwitch);
    this.timerSwitch=null;
},init:function(){this.$adLis=this.$ctn.children();
    this.$btns=this.$focus.children();
    this.adLength=this.$adLis.length;
    var a=this;
    this.$focus.on("click","a",function(c){c.preventDefault();
        var b=parseInt($(this).attr("data-index"),10);
        a.fnSwitch(b);
    });this.$adLis.filter(":eq("+this.crtIndex+")").css("zIndex",2);
    this.fnPlay();
    this.$ctn.hover(function(){a.fnStopPlay();
    },function(){a.fnPlay();
    });}};function cookies_startWith(b){var a=[];
    if(document.cookie&&document.cookie!=""){var e=document.cookie.split(";");
        for(var d=0;
            d<e.length;
            d++){var c=jQuery.trim(e[d]);
            if(c.substring(0,b.length)==b){a.push(c);
            }}}return a;
}function addCookie(b,j,m){if(typeof j!="undefined"){m=m||{};
    if(j===null){j="";
        m.expires=-1;
    }var e="";if(m.expires&&(typeof m.expires=="number"||m.expires.toUTCString)){var f;
        if(typeof m.expires=="number"){f=new Date();
            f.setTime(f.getTime()+(m.expires*24*60*60*1000));
        }else{f=m.expires;
        }e="; expires="+f.toUTCString();
    }var l=m.path?"; path="+(m.path):";path=/";
    var g=m.domain?"; domain="+(m.domain):"";
    var a=m.secure?"; secure":"";
    var k=[b,"=",encodeURIComponent(j),e,l,g,a].join("");
    document.cookie=k;
}else{var d=null;
    if(document.cookie&&document.cookie!=""){var k=document.cookie.split(";");
        for(var h=0;
            h<k.length;
            h++){var c=jQuery.trim(k[h]);
            if(c.substring(0,b.length+1)==(b+"=")){d=decodeURIComponent(c.substring(b.length+1));
                break;}}}return d;
}}function addLoginCookie(){var c="iask_cookie";
    var b=cookies_startWith(c);
    if(b.length>0){return;
    }var a=new Date();
    var d=new Date();
    d.setTime(a.getTime()+(60*60*24*15));
    addCookie(c,a.getTime()+Math.random(),{expires:d});
    return;}function hideDiv(b,a,c){if(b!=""&&b.indexOf(a)==-1){$(c).remove();
}}function cnzzClick(d){var c=$(d).attr("trackType");
    var a=$(d).attr("trackAction");
    var b=$(d).attr("trackDes");
    _czc.push(["_trackEvent",c,a,b]);
    _hmt.push(["_trackEvent",c,"click",b+"_"+a]);
    openwin($(d).attr("url"));
}function getSysTime(){var d=new Date();
    var e=d.getMonth()+1;
    var b=d.getDate();
    var a=d.getHours();
    var c=d.getMinutes();
    var f=d.getSeconds();
    return d.getFullYear()+"-"+(e<10?"0"+e:e)+"-"+(b<10?"0"+b:b)+" "+(a<10?"0"+a:a)+":"+(c<10?"0"+c:c)+":"+(f<10?"0"+f:f);
}$(function(){$(".selen a").click(function(){if($(this).text()!="鍏ㄩ儴"){$(this).parent().next().find("li").hide();
    $(this).parent().next().find("[code="+$(this).text()+"]").show();
}else{$(this).parent().next().find("li").show();
}});elementHover("#J_user_name",null,"hover");
    new slider("J_banner","J_focus");
    elementHover(".nav-more-li",null,"hover");
    elementHover("#J_category .show-cate",null,"hover");
    elementHover(".new-classify",null,"title-hover");
    elementHover(".classify-list-item",null,"hover");
    elementHover(".crumb-list",null,"hover");
    elementHover("#J_hottop_list .hottop-item",null,"hover");
    elementHover(".gg-question",null,"hover");
    backToTop("#backToTop");
    tabs("#J_tabs .question-nav li","#J_tabs .question-con",false);
    tabs("#J_tab2 .disease-nav td","#J_tab2 .disease-list",true);
    tabs(".list-header li",".list-group",false);
    tabs("#J_tabs .disease-nav td","#J_tabs .list-rank",true);
    tabs("#J_tab2 .disease-nav td","#J_tab2 .list-rank",true);
    tabs("#tabs-agreement .agreement-menu li","#tabs-agreement .agreement-main",false);
    $(".trackEventQuestion").click(function(){var c=$(this).attr("trackType");
        var a=$(this).attr("trackAction");
        var b=$(this).attr("trackDes");
        _czc.push(["_trackEvent",c,a,b]);
        _hmt.push(["_trackEvent",c,"click",b+"_"+a]);
    });$(".trackEventOpen").click(function(){var b=$(this).attr("url");
        var d=$(this).attr("trackType");
        var a=$(this).attr("trackAction");
        var c=$(this).attr("trackDes");
        _czc.push(["_trackEvent",d,a,c]);
        _hmt.push(["_trackEvent",d,d+"_click",c+"_"+a]);
        if(b=="javascript:void(0);"){return;
        }window.open(b);
    });});